// 同一のゲームを Web/PWA と iOS/Capacitor に配布するための静的ビルド。
// 既存 npm run build:www / cap:sync は引き続き検証用。
// --release は「販売できる」の意味ではない。アカウント・決済・セキュリティ確認が終わるまで公開しない。
"use strict";
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const args = new Set(process.argv.slice(2));
for (const arg of args) if (arg !== "--release" && arg !== "--web") throw new Error("Unknown option: " + arg);
const release = args.has("--release");
const web = args.has("--web");
const out = web ? path.join(ROOT, "dist", "web") : path.join(ROOT, "www");
const platform = web ? "web" : "ios";
const channel = release ? "production" : "preview";
const include = ["index.html", "manifest.webmanifest", "sw.js", "css", "js", "data", "icons", "fonts"];

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
for (const name of include) fs.cpSync(path.join(ROOT, name), path.join(out, name), { recursive: true });

// 正式配布用のアプリ内フラグをビルド時に固定する（認証/決済のセキュリティ境界ではない）。
const runtimeConfig = {
  channel, platform, allowDebug: !release, allowTestPurchases: !release,
};
fs.writeFileSync(path.join(out, "js", "runtime-env.js"),
  "// Generated by tools/build-www.js. Do not edit.\n" +
  "(function (root) { root.QPRuntime = Object.freeze(" + JSON.stringify(runtimeConfig) +
  "); })(typeof globalThis !== \"undefined\" ? globalThis : this);\n");

// 本番と試験用 Firebase プロジェクトの共用を避ける。未設定ならクラウド接続自体を停止。
// 将来の正式公開時は専用の Firebase 構成を CI の環境変数から注入する。ブラウザの apiKey は秘密ではない。
if (release) {
  let fb = null;
  if (process.env.SWORD_CREST_FIREBASE_CONFIG_JSON) {
    fb = JSON.parse(process.env.SWORD_CREST_FIREBASE_CONFIG_JSON);
    for (const key of ["apiKey", "authDomain", "projectId", "appId"]) {
      if (typeof fb[key] !== "string" || !fb[key].trim()) throw new Error("Missing Firebase config: " + key);
    }
    if (fb.projectId === "sword-crest-jp") throw new Error("Use a dedicated production Firebase project, not the prototype project");
  }
  fs.writeFileSync(path.join(out, "js", "firebase-config.js"),
    "// Generated at release build; non-secret public Firebase identifiers only.\n" +
    "window.QP_FIREBASE_CONFIG = " + JSON.stringify(fb) + ";\n");
  if (!fb) console.warn("WARNING: release build has no Firebase; account sync and cloud saves are disabled. Do NOT deploy as production yet.");
}

const html = fs.readFileSync(path.join(out, "index.html"), "utf8");
const refs = [...html.matchAll(/(?:src|href)="([^"#:]+?)(?:\?[^"]*)?"/g)].map((m) => m[1]);
const missing = refs.filter((ref) => !fs.existsSync(path.join(out, ref)));
if (missing.length) throw new Error("Missing assets: " + missing.join(", "));
console.log("Built " + channel + "/" + platform + " in " + path.relative(ROOT, out) + " (references: " + refs.length + ")");
