// Web/PWA・Capacitorに同一のゲームを出力する。Releaseは配布候補であり公開許可ではない。
"use strict";
const fs=require("node:fs"),path=require("node:path");
const ROOT=path.join(__dirname,"..");
const args=new Set(process.argv.slice(2));
for(const x of args)if(!["--release","--web"].includes(x))throw Error("Unknown option: "+x);
const release=args.has("--release"),web=args.has("--web");
const out=web?path.join(ROOT,"dist","web"):path.join(ROOT,"www");
const platform=web?"web":"ios",channel=release?"production":"preview";
function firebaseForRelease(){
  const raw=process.env.SWORD_CREST_FIREBASE_CONFIG_JSON;
  if(!raw)throw Error("Production Firebase config required: SWORD_CREST_FIREBASE_CONFIG_JSON");
  let c;
  try{c=JSON.parse(raw);}catch{throw Error("Invalid Firebase config JSON");}
  if(!c||typeof c!=="object"||Array.isArray(c))throw Error("Invalid Firebase config object");
  for(const key of ["apiKey","authDomain","projectId","appId"])if(typeof c[key]!=="string"||!c[key].trim())throw Error("Missing Firebase config: "+key);
  if(c.projectId==="sword-crest-jp"||c.authDomain==="sword-crest-jp.firebaseapp.com")throw Error("Use a dedicated production Firebase project, not the prototype project");
  if(!/^[a-z][a-z0-9-]{3,63}$/.test(c.projectId)||/[\s/]/.test(c.authDomain))throw Error("Invalid production Firebase identifiers");
  return c;
}
// 設定異常の場合、既存のビルド出力を削除せずに失敗する。
const firebase=release?firebaseForRelease():null;
function apiForRelease(){
  const raw=process.env.SWORD_CREST_API_BASE_URL;
  const siteKey=process.env.SWORD_CREST_RECAPTCHA_SITE_KEY;
  if(!raw || !siteKey)throw Error("Production HTTPS API and App Check site key required");
  let uri;
  try{uri=new URL(raw);}catch{throw Error("Invalid production API URL");}
  if(uri.protocol!=="https:" || uri.username || uri.password || uri.search || uri.hash)throw Error("Production API must use a clean HTTPS URL");
  if(!/^[A-Za-z0-9_-]{4,150}$/.test(siteKey))throw Error("Invalid App Check site key");
  return {baseUrl:uri.href.replace(/\/$/,""),recaptchaSiteKey:siteKey};
}
const api=release?apiForRelease():null;
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
for(const name of ["index.html","manifest.webmanifest","sw.js","css","js","data","icons","fonts"]){
  fs.cpSync(path.join(ROOT,name),path.join(out,name),{recursive:true});
}
fs.writeFileSync(path.join(out,"js","runtime-env.js"),
  "// Generated by tools/build-www.js\n(function(root){root.QPRuntime=Object.freeze("+
  JSON.stringify({channel,platform,allowDebug:!release,allowTestPurchases:!release})+
  ");})(typeof globalThis!==\"undefined\"?globalThis:this);\n");
if(release){
  fs.writeFileSync(path.join(out,"js","api-config.js"),
    "// Public API URL and App Check site key (not secrets).\n"+
    "window.QP_API_CONFIG="+JSON.stringify(api)+";\n");
  // Build with the Auth/App Check SDK exports only inside the release output.
  // Existing Preview vendor bundle and Firebase connection remain unchanged.
  require("esbuild").buildSync({
    entryPoints:[path.join(ROOT,"tools","firebase-entry.js")],
    bundle:true,minify:true,format:"iife",globalName:"QPFirebase",
    target:"es2019",legalComments:"eof",
    outfile:path.join(out,"js","vendor","firebase.js"),
  });
  fs.writeFileSync(path.join(out,"js","firebase-config.js"),
    "// Public Firebase app identifiers only. Never inject server or PSP secrets.\n"+
    "window.QP_FIREBASE_CONFIG="+JSON.stringify(firebase)+";\n");
  // 共通Script読み込み順を維持しつつ、開発者モードの実装を出荷しない。
  fs.writeFileSync(path.join(out,"js","debug-gate.js"),
    '"use strict";(function(root){root.QPDebugGate=Object.freeze({active:()=>false,requested:()=>false,enter:()=>false,unlocked:()=>false,leave:()=>{},takeAutoComplete:()=>false});})(typeof globalThis!=="undefined"?globalThis:this);\n');
  fs.writeFileSync(path.join(out,"js","ui","debug.js"),
    '"use strict";const DEBUG_MODE=false;for(const id of ["btnDevEnter","settingsDebug","btnSettingsShop"]){const el=document.getElementById(id);if(el){el.hidden=true;el.classList.add("hidden");}}\n');
  const swp=path.join(out,"sw.js"),sw=fs.readFileSync(swp,"utf8");
  const oldKey='const CACHE_NAME = "questparty-v1";';
  if(!sw.includes(oldKey))throw Error("PWA cache name changed: review production cache isolation");
  fs.writeFileSync(swp,sw.replace(oldKey,'const CACHE_NAME = "swordcrest-production-v1";'));
}
const html=fs.readFileSync(path.join(out,"index.html"),"utf8");
const refs=[...html.matchAll(/(?:src|href)="([^"#:]+?)(?:\?[^"]*)?"/g)].map(m=>m[1]);
const missing=refs.filter(ref=>!fs.existsSync(path.join(out,ref)));
if(missing.length)throw Error("Missing assets: "+missing.join(", "));
console.log("Built "+channel+"/"+platform+" in "+path.relative(ROOT,out)+" (references: "+refs.length+")");
